name: Preview Demo

on:
  pull_request:
    branches: [ main ]
    paths:
      - "examples/demo-react/**"
      - "packages/**"
      - "pnpm-lock.yaml"

jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with: { version: 9 }

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - run: pnpm install --frozen-lockfile
      - run: pnpm -w -F @smartqr/core build
      - run: pnpm -w -F @smartqr/react build

      - name: Install Vercel CLI
        run: pnpm add -g vercel

      - name: Pull Vercel Env
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Demo
        working-directory: examples/demo-react
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Preview
        working-directory: examples/demo-react
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
