name: Preview Demo

on:
  pull_request:
    branches: [ main ]
    paths:
      - "examples/demo-react/**"
      - "packages/**"
      - "pnpm-lock.yaml"

jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Enable Corepack (pnpm)
        run: |
          corepack enable
          corepack prepare pnpm@10.14.0 --activate
          pnpm -v

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build packages
        run: |
          pnpm -w -F @smartqr/core build
          pnpm -w -F @smartqr/react build

      - name: Pull Vercel Env
        working-directory: examples/demo-react
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: pnpm dlx vercel pull --yes --environment=preview --token="$VERCEL_TOKEN"

      - name: Build Demo
        working-directory: examples/demo-react
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: pnpm dlx vercel build --token="$VERCEL_TOKEN"

      - name: Deploy Preview
        working-directory: examples/demo-react
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: pnpm dlx vercel deploy --prebuilt --token="$VERCEL_TOKEN"
