name: Release

on:
  push:
    branches: [ main ]

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
          registry-url: 'https://registry.npmjs.org'

      - name: Enable Corepack (pnpm)
        run: |
          corepack enable
          corepack prepare pnpm@10.14.0 --activate
          pnpm -v

      - name: Install
        run: pnpm install --frozen-lockfile

      - name: Build (core then react)
        run: |
          pnpm -w -F @smartqr/core build
          pnpm -w -F @smartqr/react build

      - name: Bump versions
        run: pnpm -w changeset version

      - name: Install post-version
        run: pnpm install --
