name: Release

on:
  push:
    branches: [ main ]

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
          registry-url: 'https://registry.npmjs.org'

      - name: Install
        run: pnpm install --frozen-lockfile

      - name: Build (core then react)
        run: |
          pnpm -w -F @smartqr/core build
          pnpm -w -F @smartqr/react build

      - name: Bump versions
        run: pnpm -w changeset version

      - name: Install post-version
        run: pnpm install --no-frozen-lockfile

      - name: Publish to npm
        run: pnpm -w changeset publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
